stages:
  - quality
  - test

default:
  image: python:3.11

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

quality:
  stage: quality
  script:
    - pip install bandit
    - bandit -r . -x tests
  allow_failure: false

tests:
  stage: test
  script:
    - pip install pytest
    - pytest
